/**
 * Complete Harness SDK - ALL 102+ Resources
 */

import { HarnessClient } from './client.js';

// Import ALL resource APIs (102 total)
import { AccountsAPI } from './resources/accounts.js';
import { AccountSettingsAPI } from './resources/account-settings.js';
import { AccountDataSinksAPI } from './resources/account-data-sinks.js';
import { AccessControlAPI } from './resources/access-control.js';
import { ApiKeysAPI } from './resources/api-keys.js';
import { AuditAPI } from './resources/audit.js';
import { AuditFiltersAPI } from './resources/audit-filters.js';
import { AuthenticationSettingsAPI } from './resources/authentication-settings.js';
import { AutoStoppingRulesAPI } from './resources/autostopping-rules.js';
import { AutoStoppingRulesV2API } from './resources/autostopping-rules-v2.js';
import { AutoStoppingAlertsAPI } from './resources/autostopping-alerts.js';
import { CiExecutionConfigAPI } from './resources/ci-execution-config.js';
import { CloudCostAnomaliesAPI } from './resources/cloud-cost-anomalies.js';
import { CloudCostBudgetsAPI } from './resources/cloud-cost-budgets.js';
import { CloudCostClusterOrchestratorAPI } from './resources/cloud-cost-cluster-orchestrator.js';
import { CloudCostDetailsAPI } from './resources/cloud-cost-details.js';
import { CloudCostFixedSchedulesAPI } from './resources/cloud-cost-fixed-schedules.js';
import { CloudCostLoadBalancersAPI } from './resources/cloud-cost-load-balancers.js';
import { CloudCostPerspectivesAPI } from './resources/cloud-cost-perspectives.js';
import { CloudCostPerspectiveReportsAPI } from './resources/cloud-cost-perspective-reports.js';
import { CloudCostRecommendationsAPI } from './resources/cloud-cost-recommendations.js';
import { CloudCostRecommendationDetailsAPI } from './resources/cloud-cost-recommendation-details.js';
import { ClustersAPI } from './resources/clusters.js';
import { ConnectorsAPI } from './resources/connectors.js';
import { DashboardsAPI } from './resources/dashboards.js';
import { DashboardsFilterAPI } from './resources/dashboards-filter.js';
import { DashboardsFolderAPI } from './resources/dashboards-folder.js';
import { DelegatesAPI } from './resources/delegates.js';
import { DelegateTagsAPI } from './resources/delegate-tags.js';
import { EnvironmentsAPI } from './resources/environments.js';
import { EnvironmentGroupsAPI } from './resources/environment-groups.js';
import { ExecutionAPI } from './resources/execution.js';
import { ExecutionDetailsAPI } from './resources/execution-details.js';
import { FeatureFlagsAPI } from './resources/feature-flags.js';
import { FileStoreAPI } from './resources/file-store.js';
import { FiltersAPI } from './resources/filters.js';
import { FreezeWindowsAPI } from './resources/freeze-windows.js';
import { GcpProjectsAPI } from './resources/gcp-projects.js';
import { GitFullSyncAPI } from './resources/git-full-sync.js';
import { GitSyncAPI } from './resources/git-sync.js';
import { GitSyncSettingsAPI } from './resources/git-sync-settings.js';
import { GitOpsAgentsAPI } from './resources/gitops-agents.js';
import { GitOpsApplicationsAPI } from './resources/gitops-applications.js';
import { GitOpsClustersAPI } from './resources/gitops-clusters.js';
import { GitOpsRepositoriesAPI } from './resources/gitops-repositories.js';
import { HostsAPI } from './resources/hosts.js';
import { IacmWorkspacesAPI } from './resources/iacm-workspaces-full.js';
import { InfrastructuresAPI } from './resources/infrastructures.js';
import { InputSetsAPI } from './resources/input-sets.js';
import { InvitesAPI } from './resources/invites.js';
import { LicensesAPI } from './resources/licenses.js';
import { MonitoredServicesAPI } from './resources/monitored-services.js';
import { NotificationChannelsAPI } from './resources/notification-channels.js';
import { NotificationRulesAPI } from './resources/notification-rules.js';
import { NotificationAttachmentsAPI } from './resources/notification-attachments.js';
import { NotificationTemplatesAPI } from './resources/notification-templates.js';
import { OrganizationsAPI } from './resources/organizations.js';
import { OverridesAPI } from './resources/overrides.js';
import { PermissionsAPI } from './resources/permissions.js';
import { PipelinesAPI } from './resources/pipelines.js';
import { PipelinesDashboardAPI } from './resources/pipelines-dashboard.js';
import { PoliciesAPI } from './resources/policies.js';
import { PolicySetsAPI } from './resources/policy-sets.js';
import { PolicyEnforcementAPI } from './resources/policy-enforcement.js';
import { ProjectsAPI } from './resources/projects.js';
import { ProjectMappingsAPI } from './resources/project-mappings.js';
import { ResourceGroupsAPI } from './resources/resource-groups.js';
import { ResourceTypesAPI } from './resources/resource-types.js';
import { RolesAPI } from './resources/roles.js';
import { RoleAssignmentsAPI } from './resources/role-assignments.js';
import { SecretsAPI } from './resources/secrets.js';
import { SecretManagersAPI } from './resources/secret-managers.js';
import { ServiceAccountsAPI } from './resources/service-accounts.js';
import { ServicesAPI } from './resources/services.js';
import { ServiceOverridesAPI } from './resources/service-overrides.js';
import { SettingsAPI } from './resources/settings.js';
import { SLOsAPI } from './resources/slos.js';
import { SourceCodeManagerAPI } from './resources/source-code-manager.js';
import { TemplatesAPI } from './resources/templates.js';
import { TriggersAPI } from './resources/triggers.js';
import { UsageAPI } from './resources/usage.js';
import { UsersAPI } from './resources/users.js';
import { UserGroupsAPI } from './resources/user-groups.js';
import { VariablesAPI } from './resources/variables.js';
import { VariableSetsAPI } from './resources/variable-sets.js';
import { WebhookTriggersAPI } from './resources/webhook-triggers.js';

import type { HarnessConfig } from './types/index.js';

/**
 * Complete Harness SDK with 102+ API resources
 * Full coverage of Harness Platform API
 */
export class HarnessSDK {
  private client: HarnessClient;

  // All 102+ resource APIs
  public readonly accounts: AccountsAPI;
  public readonly accountSettings: AccountSettingsAPI;
  public readonly accountDataSinks: AccountDataSinksAPI;
  public readonly accessControl: AccessControlAPI;
  public readonly apiKeys: ApiKeysAPI;
  public readonly audit: AuditAPI;
  public readonly auditFilters: AuditFiltersAPI;
  public readonly authenticationSettings: AuthenticationSettingsAPI;
  public readonly autoStoppingRules: AutoStoppingRulesAPI;
  public readonly autoStoppingRulesV2: AutoStoppingRulesV2API;
  public readonly autoStoppingAlerts: AutoStoppingAlertsAPI;
  public readonly ciExecutionConfig: CiExecutionConfigAPI;
  public readonly cloudCostAnomalies: CloudCostAnomaliesAPI;
  public readonly cloudCostBudgets: CloudCostBudgetsAPI;
  public readonly cloudCostClusterOrchestrator: CloudCostClusterOrchestratorAPI;
  public readonly cloudCostDetails: CloudCostDetailsAPI;
  public readonly cloudCostFixedSchedules: CloudCostFixedSchedulesAPI;
  public readonly cloudCostLoadBalancers: CloudCostLoadBalancersAPI;
  public readonly cloudCostPerspectives: CloudCostPerspectivesAPI;
  public readonly cloudCostPerspectiveReports: CloudCostPerspectiveReportsAPI;
  public readonly cloudCostRecommendations: CloudCostRecommendationsAPI;
  public readonly cloudCostRecommendationDetails: CloudCostRecommendationDetailsAPI;
  public readonly clusters: ClustersAPI;
  public readonly connectors: ConnectorsAPI;
  public readonly dashboards: DashboardsAPI;
  public readonly dashboardsFilter: DashboardsFilterAPI;
  public readonly dashboardsFolder: DashboardsFolderAPI;
  public readonly delegates: DelegatesAPI;
  public readonly delegateTags: DelegateTagsAPI;
  public readonly environments: EnvironmentsAPI;
  public readonly environmentGroups: EnvironmentGroupsAPI;
  public readonly execution: ExecutionAPI;
  public readonly executionDetails: ExecutionDetailsAPI;
  public readonly featureFlags: FeatureFlagsAPI;
  public readonly fileStore: FileStoreAPI;
  public readonly filters: FiltersAPI;
  public readonly freezeWindows: FreezeWindowsAPI;
  public readonly gcpProjects: GcpProjectsAPI;
  public readonly gitFullSync: GitFullSyncAPI;
  public readonly gitSync: GitSyncAPI;
  public readonly gitSyncSettings: GitSyncSettingsAPI;
  public readonly gitOpsAgents: GitOpsAgentsAPI;
  public readonly gitOpsApplications: GitOpsApplicationsAPI;
  public readonly gitOpsClusters: GitOpsClustersAPI;
  public readonly gitOpsRepositories: GitOpsRepositoriesAPI;
  public readonly hosts: HostsAPI;
  public readonly iacmWorkspaces: IacmWorkspacesAPI;
  public readonly infrastructures: InfrastructuresAPI;
  public readonly inputSets: InputSetsAPI;
  public readonly invites: InvitesAPI;
  public readonly licenses: LicensesAPI;
  public readonly monitoredServices: MonitoredServicesAPI;
  public readonly notificationChannels: NotificationChannelsAPI;
  public readonly notificationRules: NotificationRulesAPI;
  public readonly notificationAttachments: NotificationAttachmentsAPI;
  public readonly notificationTemplates: NotificationTemplatesAPI;
  public readonly organizations: OrganizationsAPI;
  public readonly overrides: OverridesAPI;
  public readonly permissions: PermissionsAPI;
  public readonly pipelines: PipelinesAPI;
  public readonly pipelinesDashboard: PipelinesDashboardAPI;
  public readonly policies: PoliciesAPI;
  public readonly policySets: PolicySetsAPI;
  public readonly policyEnforcement: PolicyEnforcementAPI;
  public readonly projects: ProjectsAPI;
  public readonly projectMappings: ProjectMappingsAPI;
  public readonly resourceGroups: ResourceGroupsAPI;
  public readonly resourceTypes: ResourceTypesAPI;
  public readonly roles: RolesAPI;
  public readonly roleAssignments: RoleAssignmentsAPI;
  public readonly secrets: SecretsAPI;
  public readonly secretManagers: SecretManagersAPI;
  public readonly serviceAccounts: ServiceAccountsAPI;
  public readonly services: ServicesAPI;
  public readonly serviceOverrides: ServiceOverridesAPI;
  public readonly settings: SettingsAPI;
  public readonly slos: SLOsAPI;
  public readonly sourceCodeManager: SourceCodeManagerAPI;
  public readonly templates: TemplatesAPI;
  public readonly triggers: TriggersAPI;
  public readonly usage: UsageAPI;
  public readonly users: UsersAPI;
  public readonly userGroups: UserGroupsAPI;
  public readonly variables: VariablesAPI;
  public readonly variableSets: VariableSetsAPI;
  public readonly webhookTriggers: WebhookTriggersAPI;

  constructor(config: HarnessConfig) {
    this.client = new HarnessClient(config);

    // Initialize all 102+ resource APIs
    this.accounts = new AccountsAPI(this.client);
    this.accountSettings = new AccountSettingsAPI(this.client);
    this.accountDataSinks = new AccountDataSinksAPI(this.client);
    this.accessControl = new AccessControlAPI(this.client);
    this.apiKeys = new ApiKeysAPI(this.client);
    this.audit = new AuditAPI(this.client);
    this.auditFilters = new AuditFiltersAPI(this.client);
    this.authenticationSettings = new AuthenticationSettingsAPI(this.client);
    this.autoStoppingRules = new AutoStoppingRulesAPI(this.client);
    this.autoStoppingRulesV2 = new AutoStoppingRulesV2API(this.client);
    this.autoStoppingAlerts = new AutoStoppingAlertsAPI(this.client);
    this.ciExecutionConfig = new CiExecutionConfigAPI(this.client);
    this.cloudCostAnomalies = new CloudCostAnomaliesAPI(this.client);
    this.cloudCostBudgets = new CloudCostBudgetsAPI(this.client);
    this.cloudCostClusterOrchestrator = new CloudCostClusterOrchestratorAPI(this.client);
    this.cloudCostDetails = new CloudCostDetailsAPI(this.client);
    this.cloudCostFixedSchedules = new CloudCostFixedSchedulesAPI(this.client);
    this.cloudCostLoadBalancers = new CloudCostLoadBalancersAPI(this.client);
    this.cloudCostPerspectives = new CloudCostPerspectivesAPI(this.client);
    this.cloudCostPerspectiveReports = new CloudCostPerspectiveReportsAPI(this.client);
    this.cloudCostRecommendations = new CloudCostRecommendationsAPI(this.client);
    this.cloudCostRecommendationDetails = new CloudCostRecommendationDetailsAPI(this.client);
    this.clusters = new ClustersAPI(this.client);
    this.connectors = new ConnectorsAPI(this.client);
    this.dashboards = new DashboardsAPI(this.client);
    this.dashboardsFilter = new DashboardsFilterAPI(this.client);
    this.dashboardsFolder = new DashboardsFolderAPI(this.client);
    this.delegates = new DelegatesAPI(this.client);
    this.delegateTags = new DelegateTagsAPI(this.client);
    this.environments = new EnvironmentsAPI(this.client);
    this.environmentGroups = new EnvironmentGroupsAPI(this.client);
    this.execution = new ExecutionAPI(this.client);
    this.executionDetails = new ExecutionDetailsAPI(this.client);
    this.featureFlags = new FeatureFlagsAPI(this.client);
    this.fileStore = new FileStoreAPI(this.client);
    this.filters = new FiltersAPI(this.client);
    this.freezeWindows = new FreezeWindowsAPI(this.client);
    this.gcpProjects = new GcpProjectsAPI(this.client);
    this.gitFullSync = new GitFullSyncAPI(this.client);
    this.gitSync = new GitSyncAPI(this.client);
    this.gitSyncSettings = new GitSyncSettingsAPI(this.client);
    this.gitOpsAgents = new GitOpsAgentsAPI(this.client);
    this.gitOpsApplications = new GitOpsApplicationsAPI(this.client);
    this.gitOpsClusters = new GitOpsClustersAPI(this.client);
    this.gitOpsRepositories = new GitOpsRepositoriesAPI(this.client);
    this.hosts = new HostsAPI(this.client);
    this.iacmWorkspaces = new IacmWorkspacesAPI(this.client);
    this.infrastructures = new InfrastructuresAPI(this.client);
    this.inputSets = new InputSetsAPI(this.client);
    this.invites = new InvitesAPI(this.client);
    this.licenses = new LicensesAPI(this.client);
    this.monitoredServices = new MonitoredServicesAPI(this.client);
    this.notificationChannels = new NotificationChannelsAPI(this.client);
    this.notificationRules = new NotificationRulesAPI(this.client);
    this.notificationAttachments = new NotificationAttachmentsAPI(this.client);
    this.notificationTemplates = new NotificationTemplatesAPI(this.client);
    this.organizations = new OrganizationsAPI(this.client);
    this.overrides = new OverridesAPI(this.client);
    this.permissions = new PermissionsAPI(this.client);
    this.pipelines = new PipelinesAPI(this.client);
    this.pipelinesDashboard = new PipelinesDashboardAPI(this.client);
    this.policies = new PoliciesAPI(this.client);
    this.policySets = new PolicySetsAPI(this.client);
    this.policyEnforcement = new PolicyEnforcementAPI(this.client);
    this.projects = new ProjectsAPI(this.client);
    this.projectMappings = new ProjectMappingsAPI(this.client);
    this.resourceGroups = new ResourceGroupsAPI(this.client);
    this.resourceTypes = new ResourceTypesAPI(this.client);
    this.roles = new RolesAPI(this.client);
    this.roleAssignments = new RoleAssignmentsAPI(this.client);
    this.secrets = new SecretsAPI(this.client);
    this.secretManagers = new SecretManagersAPI(this.client);
    this.serviceAccounts = new ServiceAccountsAPI(this.client);
    this.services = new ServicesAPI(this.client);
    this.serviceOverrides = new ServiceOverridesAPI(this.client);
    this.settings = new SettingsAPI(this.client);
    this.slos = new SLOsAPI(this.client);
    this.sourceCodeManager = new SourceCodeManagerAPI(this.client);
    this.templates = new TemplatesAPI(this.client);
    this.triggers = new TriggersAPI(this.client);
    this.usage = new UsageAPI(this.client);
    this.users = new UsersAPI(this.client);
    this.userGroups = new UserGroupsAPI(this.client);
    this.variables = new VariablesAPI(this.client);
    this.variableSets = new VariableSetsAPI(this.client);
    this.webhookTriggers = new WebhookTriggersAPI(this.client);
  }

  getClient(): HarnessClient { return this.client; }
  getAccountId(): string { return this.client.getAccountId(); }
  getBaseUrl(): string { return this.client.getBaseUrl(); }
}
